[en]
title = "My blog"
weight = 1
LanguageName = "VN"
contentDir = "content/english"

[ar]
title = "blog"
contentDir = "content/arabic" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "vN"
[ar.params]
description = "أنا أعمل كمطورة ويب في شركة س"